// Code generated by entc, DO NOT EDIT.

package member

import (
	"time"
)

const (
	// Label holds the string label denoting the member type in the database.
	Label = "member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// EdgeRoles holds the string denoting the roles edge name in mutations.
	EdgeRoles = "roles"
	// EdgeDeveloperOf holds the string denoting the developerof edge name in mutations.
	EdgeDeveloperOf = "developerOf"
	// EdgeManagerOf holds the string denoting the managerof edge name in mutations.
	EdgeManagerOf = "managerOf"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// Table holds the table name of the member in the database.
	Table = "members"
	// RolesTable is the table that holds the roles relation/edge. The primary key declared below.
	RolesTable = "member_roles"
	// RolesInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RolesInverseTable = "roles"
	// DeveloperOfTable is the table that holds the developerOf relation/edge. The primary key declared below.
	DeveloperOfTable = "organization_developers"
	// DeveloperOfInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	DeveloperOfInverseTable = "organizations"
	// ManagerOfTable is the table that holds the managerOf relation/edge. The primary key declared below.
	ManagerOfTable = "organization_managers"
	// ManagerOfInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	ManagerOfInverseTable = "organizations"
	// TasksTable is the table that holds the tasks relation/edge. The primary key declared below.
	TasksTable = "task_assignees"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
)

// Columns holds all SQL columns for member fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldEmail,
}

var (
	// RolesPrimaryKey and RolesColumn2 are the table columns denoting the
	// primary key for the roles relation (M2M).
	RolesPrimaryKey = []string{"member_id", "role_id"}
	// DeveloperOfPrimaryKey and DeveloperOfColumn2 are the table columns denoting the
	// primary key for the developerOf relation (M2M).
	DeveloperOfPrimaryKey = []string{"organization_id", "member_id"}
	// ManagerOfPrimaryKey and ManagerOfColumn2 are the table columns denoting the
	// primary key for the managerOf relation (M2M).
	ManagerOfPrimaryKey = []string{"organization_id", "member_id"}
	// TasksPrimaryKey and TasksColumn2 are the table columns denoting the
	// primary key for the tasks relation (M2M).
	TasksPrimaryKey = []string{"task_id", "member_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
)
