// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
